#!/bin/bash

echo "🔧 Setting up MarketPulse Security Group"
echo "======================================="

# This script helps you create a reusable security group
# Run this once, then reuse the security group for future instances

echo "📋 To create a reusable security group:"
echo ""
echo "1. Go to AWS Console → EC2 → Security Groups"
echo "2. Click 'Create security group'"
echo "3. Name it: 'MarketPulse-Production'"
echo "4. Description: 'Security group for MarketPulse application'"
echo "5. Add these inbound rules:"
echo ""
echo "   Rule 1:"
echo "   - Type: Custom TCP"
echo "   - Port: 22"
echo "   - Source: Your IP (for SSH access)"
echo "   - Description: SSH Access"
echo ""
echo "   Rule 2:"
echo "   - Type: Custom TCP"
echo "   - Port: 3000"
echo "   - Source: 0.0.0.0/0"
echo "   - Description: MarketPulse Frontend"
echo ""
echo "   Rule 3:"
echo "   - Type: Custom TCP"
echo "   - Port: 8080"
echo "   - Source: 0.0.0.0/0"
echo "   - Description: MarketPulse User Service"
echo ""
echo "   Rule 4:"
echo "   - Type: Custom TCP"
echo "   - Port: 8081"
echo "   - Source: 0.0.0.0/0"
echo "   - Description: MarketPulse Article Service"
echo ""
echo "   Rule 5:"
echo "   - Type: Custom TCP"
echo "   - Port: 5001"
echo "   - Source: 0.0.0.0/0"
echo "   - Description: MarketPulse Analysis Service"
echo ""
echo "6. Click 'Create security group'"
echo ""
echo "✅ Now you can reuse this security group for all future MarketPulse deployments!"
echo "💡 When launching new EC2 instances, select 'MarketPulse-Production' instead of creating new ones"
