apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-service
  namespace: marketpulse
  labels:
    app: analysis-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-service
  template:
    metadata:
      labels:
        app: analysis-service
    spec:
      containers:
      - name: analysis-service
        image: marketpulse/analysis-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: REDIS_HOST
          value: "REDIS_HOST"
        - name: REDIS_PORT
          value: "6379"
        - name: ARTICLE_BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: marketpulse-config
              key: ARTICLE_BATCH_SIZE
        - name: NEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: marketpulse-secrets
              key: news-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service
  namespace: marketpulse
  labels:
    app: analysis-service
spec:
  selector:
    app: analysis-service
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
  type: ClusterIP

