apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-service
  namespace: marketpulse
  labels:
    app: article-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: article-service
  template:
    metadata:
      labels:
        app: article-service
    spec:
      containers:
      - name: article-service
        image: marketpulse/article-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://POSTGRES_ARTICLES_HOST:5432/marketpulse_articles"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: marketpulse-secrets
              key: postgres-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: marketpulse-secrets
              key: postgres-password
        - name: SPRING_REDIS_HOST
          value: "REDIS_HOST"
        - name: SPRING_REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: article-service
  namespace: marketpulse
  labels:
    app: article-service
spec:
  selector:
    app: article-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

