apiVersion: v1
kind: Secret
metadata:
  name: marketpulse-secrets
  namespace: marketpulse
type: Opaque
data:
  # Base64 encoded values - you'll need to replace these with actual encoded values
  postgres-user: bWFya2V0cHVsc2VfdXNlcg==  # marketpulse_user
  postgres-password: bWFya2V0cHVsc2VfcGFzcw==  # marketpulse_pass
  jwt-secret: bXlfc2VjcmV0X2p3dF9rZXk=  # my_secret_jwt_key
  news-api-key: eW91cl9uZXdzX2FwaV9rZXk=  # your_news_api_key
  alpha-vantage-key: eW91cl9hbHBoYV92YW50YWdlX2tleQ==  # your_alpha_vantage_key
  finnhub-api-key: eW91cl9maW5uaHViX2tleQ==  # your_finnhub_key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: marketpulse-config
  namespace: marketpulse
data:
  # Database configuration
  POSTGRES_DB_USERS: "marketpulse_users"
  POSTGRES_DB_ARTICLES: "marketpulse_articles"
  
  # Service ports
  USER_SERVICE_PORT: "8080"
  ARTICLE_SERVICE_PORT: "8080"
  ANALYSIS_SERVICE_PORT: "5001"
  
  # JWT configuration
  JWT_EXPIRATION: "86400000"
  
  # Analysis service configuration
  ARTICLE_BATCH_SIZE: "15"

